# Site settings
title: 
header-img: img/home-bg.png
email: mariecain27@gmail.com
copyright_name: mariecain27
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mariecain27
learn_profile: mariecain27
email_username: mariecain27@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
